### ISSUE TITLE
I can't open this editor for my csv file

### ISSUE THREAD

**Issue by WeiTing108AB8001** [janisdd/vscode-edit-csv#74] opened 2021-10-26 02:49 UTC
### What OS?
- Windows10

### Version?
- vs code plugin

### Description
I can't open this csv editor for my csv file that can work in other app such as excel.
I have tried reopen my vscode and it didn't help.
I created a temp csv file and try to open its csv editor in vscode, it can work.

### Expected behavior
Resolve the problem with my csv file that can't work by this editor.

### Steps to reproduce
1.Install the extension in vscode.
2.click my csv file in EXPLORER of vscode
3.click the upper right "Edit csv"
4.pop up a bottom right window show "Open a csv file first to show the csv editor"

**Comment by janisdd** [comment] 2021-11-03 19:44
@WeiTing108AB8001  I need more information about the issue...

**Comment by janisdd** [comment] 2021-11-12 12:18
I guess this can be closed as it is probably connected with the detected file language.

**Closed by janisdd** 2021-11-12 12:18 UTC
Labels: missing information

**Comment by astef** [comment] 2022-02-01 13:59
I see "Open a csv file first to show the csv editor" as well, even with correct language detected:

![image](https://user-images.githubusercontent.com/846683/151982035-16db7bde-4c0d-4ea7-8f25-e0df1f0cdc6f.png)

**Comment by janisdd** [comment] 2022-02-01 16:24
I just tested again on a windows 7 vm with vs code 1.63.2 too and it works...

Is there anything special about the csv file?
Or can you share the file? Does it happen with all csv files?
Does it work if you only use, say the first 10 lines of the file (as a new csv file)?

**Comment by astef** [comment] 2022-02-01 17:05
It happens with any csv files, and I have reproduced similar issue with https://marketplace.visualstudio.com/items?itemName=estivo.csv-editor - nothing happens when I run command.

**Comment by janisdd** [comment] 2022-02-01 19:58
I have a comment in the code that there is an issue with files >50MB because then `vscode.window.activeTextEditor ` will be falsy...
Maybe all your csv files are larger than 50MB?

The only other thing might be that the csv detection is not working...
(The last option would be to add more logging and check every step of the csv detection)

**Comment by astef** [comment] 2022-02-01 20:07
You're right, all my files are ~60MB, and with smaller files it works! Thank you!

**Comment by janisdd** [comment] 2022-02-01 20:36
Unfortunately this is a vs code limitation... I'll change the message to include this scenario.

And trying to use the extension with files >50MB would be extremely slow anyways ;D
