### ISSUE TITLE
will not render medium sized csv

### ISSUE THREAD

**Issue by mjh7** [janisdd/vscode-edit-csv#46] opened 2020-09-30 19:43 UTC
I have noticed this plug-in processes for a second, flashes a render for a split second and then hangs on "rendering table" when trying to work with csv's of even moderate size. The current file I'm working with is ~2.6MB, but I have noticed this many times and I am just getting around to reporting.

I remember reading something about rendering disabled above 50MB?

One of my primary uses is to check and apply alternate formatting such as when one application needs strings quoted and another application needs them unquoted - is there a way to force it to render at least a portion of larger files where you can preview and apply such read/write options?

I am using Windows 10, latest version of VS Code and extension as far as I know. Thanks!

**Comment by janisdd** [comment] 2020-09-30 20:14
Not sure what you mean by "flashes a render". The hanging from "rendering table" is normal, handsontable is doing some work there to measure and render everything. In my windows (7) vm it takes ~14s to render a 12MB (10 000 lines) file from click edit to interactive. ~2.6MB take 3-4s... 
May I ask you what your processor clock speed is?

I think 50MB is the max possible. Even though vs code can handle it, extensions are probably still limited to 50MB (I checked with 62MB and it's not recognized by the extension).

If you are dealing with large files and only want to change the formatting a small python/node script would probably a better option here?

**Comment by mjh7** [comment] 2020-09-30 21:08
Thanks. I mean that the content area of the UI appears to show data for a split second (but it's too fast to tell what this content really is). My processor is Xeon E3-1535N v5 @ 2,90GHz

When I say "hang" I mean it frequently never renders, waited minutes. Python scripts would be an alternative, but the GUI is much easier to check what formatting is applied and change flexibly when the parameters are frequently different.

I tried a couple more things that might help narrow down my issue - copying the original file from network share to local drive did not solve the problem, but I did an alternative export with strings not quoted, and this rendered fine in a few seconds. The version of the file with quoted string fields still never renders for me - so maybe this is an issue specifically when the source csv has quoted fields?

**Comment by janisdd** [comment] 2020-09-30 21:22
Ah, maybe you see the the read options / write options / preview panel as it is open initially and collapsed as soon as possible... I'll try to change the css to start with a collapsed panel and then apply the `optionsBarAppearance` afterwards. Maybe this is that flashy.

Hm... never thought that quoted string could make a difference performance wise but I'll check that in the next couple of days. Thanks for the hint!

**Comment by mjh7** [comment] 2020-10-01 17:34
Hi again, I don't want you to spend more time than necessary - I noticed something else. I opened and rendered a 1.5MB csv with quoted values and comma separators without issue. The one I can't render has quoted values and pipe (|) delimiting. Just in case this combination is relevant....

**Comment by janisdd** [comment] 2020-10-01 20:44
Just a quick update on this (also for later documentation). There is a performance issue with guessing the delimiter. This is also noted at PapaParse, issue 624 (don't want to link there/scare them).

The core problem is an unknown delimiter with all quoted fields. Papaparse tries different delimiters and uses the one that produces the most valid fields. For this it only uses the first X (default to 10) lines.

From my testing the problem should only occur when the last field in a row misses closing quotes.
This causes papaparse to not recognize the new line character as it assumes it is inside a multi line field (closing quotes aren't not found yet). This combined with the unknown delimiter it never finds a valid field or row and processes the whole file not just 10 lines.

I'll do some more digging but could you validate/lint your csv (e.g. online validator) that cause that problem and check if there are some quotes missing?

**Comment by janisdd** [comment] 2020-10-01 22:25
Another problem I noticed when the last field (or any field?) in a row misses the closing quotes the new line character is not properly recognized. This is because guessNewLine removes all text inside `"..."` and then guesses the new line character. because of the used regex and missing quotes all new lines are removed and we default to `\n`.

**Comment by janisdd** [comment] 2020-10-10 19:40
I think I found a fix for this issue... However, I can't test it because I have no data...

@mjh7 Could you provide some changed (sensitive data removed) sample data to reproduce? 
If this is not possible, can you build and install the latest version in master branch and check if it is fixed?
Or I just release the new version and we hope for the best...
What do you think?

**Comment by mjh7** [comment] 2020-10-11 01:50
Thank you - I will see what I can do about de-sensitizing my dataset, but I’m actually out of town so it might be 2 or 3 days

**Comment by janisdd** [comment] 2020-10-27 17:50
@mjh7 Did you find some time to check the data? If not I can just release the update and you can check with your data again.

**Comment by janisdd** [comment] 2020-11-07 15:01
Guess this is fixed unless stated otherwise

**Closed by janisdd** 2020-11-07 15:01 UTC

**Comment by mjh7** [comment] 2020-11-07 17:15
Hi thanks for your attention to this .Sorry I've been really swamped, I
will follow up but it might be a little while longer.
