### ISSUE TITLE
When delimiter is `, `(with a space after comma), and there is `,` or `, ` in the cell, the read function will break the cell by `,` or `, `

### ISSUE THREAD

**Issue by wenmin92** [janisdd/vscode-edit-csv#58] opened 2021-04-05 15:58 UTC
### What OS?
- Windows

### Version?
- vs code plugin

### Description
When delimiter is `, `(with a space after comma), and there is `,` or `, ` in the cell(with quotes), the read function will break the cell by `,` or `, `.

### Steps to reproduce
1. Add csv data, for example, `x, "y,y", z`
2. Use _Edit as csv_
3. Render error occurs

Data: 
```
a, b, c
x, "y,y", z
```
CSV edit view:
![image](https://user-images.githubusercontent.com/6901815/113594813-c2924e00-966a-11eb-9791-7c6df684480e.png)

**Comment by janisdd** [comment] 2021-04-06 16:43
I can reproduce this... It seems to be an issue with any delimiter longer than 1 character (and any cell contains a quoted field)
I'll look into this

**Comment by janisdd** [comment] 2021-04-10 12:06
This seems to be a bug in papaparse, thanks for submitting this!

This will be fixed with the next update.

Note that with `, ` (comma and whitespace) your input don't need quotes

```
a, b, c
x, y,y, z
```
will be parsed into the same data

**Closed** 2021-04-14 18:27 UTC
Labels: released next update
